In [1]:

import pickle
import numpy as np

In [3]:
ohe_sex = pickle.load(open('ohe_sex.pkl','rb'))
ohe_embarked = pickle.load(open('ohe_embarked.pkl','rb'))
clf = pickle.load(open('clf.pkl','rb'))


In [26]:
# Assume user input
# Pclass/gender/age/SibSp/Parch/Fare/Embarked
test_input = np.array([2, 'male', 31.0, 0, 0, 10.5, 'S'],dtype=object).reshape(1,7)

In [27]:
test_input

array([[2, 'male', 31.0, 0, 0, 10.5, 'S']], dtype=object)

In [28]:
test_input_sex = ohe_sex.transform(test_input[:,1].reshape(1,1))

C:\Users\trukk\miniconda3\envs\myenv\lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


In [29]:
test_input_sex

array([[0, 1]])

In [30]:
test_input_embarked = ohe_embarked.transform(test_input[:,-1].reshape(1,1))

In [31]:
test_input_embarked

array([[0, 0, 1]])

In [32]:
test_input_age = test_input[:,2].reshape(1,1)

In [33]:
test_input_transformed = np.concatenate((test_input[:,[0,3,4,5]],test_input_age,test_input_sex,test_input_embarked),axis=1)

In [34]:
test_input_transformed.shape

(1, 10)

In [35]:
clf.predict(test_input_transformed)

array([0], dtype=int64)